export const Decimal = 8
export const KeyAccept = [
    'Digit1',
    'Digit2',
    'Digit3',
    'Digit4',
    'Digit5',
    'Digit6',
    'Digit7',
    'Digit8',
    'Digit9',
    'Digit0',
    'Numpad1',
    'Numpad2',
    'Numpad3',
    'Numpad4',
    'Numpad5',
    'Numpad6',
    'Numpad7',
    'Numpad8',
    'Numpad9',
    'Numpad0',
    'Period',
    'Backspace',
    'Delete',
    'ArrowLeft',
    'ArrowRight',
    'ArrowDown',
    'ArrowUp',
    'ShiftRight',
    'ShiftLeft',
    'CapsLock',
    'MetaLeft',
    'MetaRight',
    'ControlLeft',
    'ControlRight',
    'Enter',
    'NumpadEnter',
    'Numpad0',
    'Numpad1',
    'Numpad2',
    'Numpad3',
    'Numpad4',
    'Numpad5',
    'Numpad6',
    'Numpad7',
    'Numpad8',
    'Numpad9',
    'NumpadDecimal',
    'NumpadSubtract',
]
export const ChainLabel: Record<number, string> = {
    97: 'BSC Testnet',
    56: 'BSC Mainnet',
}
